AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  nerdjokes:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 6
      Role: 'arn:aws:iam::971579260814:role/tech-jokes-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
